### ISSUE TITLE
bug: can't delete a crosschat channel

### ISSUE THREAD

**Issue by onerandomusername** [vcokltfre/crosschat#3]
#### Command
`/channels delete name: development`

#### Traceback
```py
crosschat    | Ignoring exception in on_slash_command_error
crosschat    | Traceback (most recent call last):
crosschat    |   File "/root/.cache/pypoetry/virtualenvs/crosschat-TFcQMFAJ-py3.10/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 274, in invoke
crosschat    |     await call_param_func(self.callback, inter, self.cog, **kwargs)
crosschat    |   File "/root/.cache/pypoetry/virtualenvs/crosschat-TFcQMFAJ-py3.10/lib/python3.10/site-packages/disnake/ext/commands/params.py", line 678, in call_param_func
crosschat    |     return await maybe_coroutine(safe_call, function, **kwargs)
crosschat    |   File "/root/.cache/pypoetry/virtualenvs/crosschat-TFcQMFAJ-py3.10/lib/python3.10/site-packages/disnake/utils.py", line 555, in maybe_coroutine
crosschat    |     return await value
crosschat    |   File "/bot/src/exts/control/admin.py", line 65, in delete_channel
crosschat    |     channel = await Channel.get(name=name)
crosschat    |   File "/root/.cache/pypoetry/virtualenvs/crosschat-TFcQMFAJ-py3.10/lib/python3.10/site-packages/ormar/models/metaclass.py", line 649, in __getattr__
crosschat    |     return object.__getattribute__(self, item)
crosschat    | AttributeError: 'ModelMetaclass' object has no attribute 'get'
crosschat    |
crosschat    | The above exception was the direct cause of the following exception:
crosschat    |
crosschat    | Traceback (most recent call last):
crosschat    |   File "/root/.cache/pypoetry/virtualenvs/crosschat-TFcQMFAJ-py3.10/lib/python3.10/site-packages/disnake/client.py", line 515, in _run_event
crosschat    |     await coro(*args, **kwargs)
crosschat    |   File "/bot/src/exts/errors.py", line 15, in on_slash_command_error
crosschat    |     await self.handle_interaction_error(itr, error)
crosschat    |   File "/bot/src/exts/errors.py", line 36, in handle_interaction_error
crosschat    |     raise error
crosschat    |   File "/root/.cache/pypoetry/virtualenvs/crosschat-TFcQMFAJ-py3.10/lib/python3.10/site-packages/disnake/ext/commands/interaction_bot_base.py", line 1346, in process_application_commands
crosschat    |     await app_command.invoke(interaction)
crosschat    |   File "/root/.cache/pypoetry/virtualenvs/crosschat-TFcQMFAJ-py3.10/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 579, in invoke
crosschat    |     await self.invoke_children(inter)
crosschat    |   File "/root/.cache/pypoetry/virtualenvs/crosschat-TFcQMFAJ-py3.10/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 564, in invoke_children
crosschat    |     await subcmd.invoke(inter, **kwargs)
crosschat    |   File "/root/.cache/pypoetry/virtualenvs/crosschat-TFcQMFAJ-py3.10/lib/python3.10/site-packages/disnake/ext/commands/slash_core.py", line 283, in invoke
crosschat    |     raise CommandInvokeError(exc) from exc
crosschat    | disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'ModelMetaclass' object has no attribute 'get'
```

**Comment by vcokltfre** [comment]
Fixed in https://github.com/vcokltfre/crosschat/commit/79526603d8cf20eaa2aa94e5daed4384d9778929
